### PR TITLE
Add fixed intensity indicator concept

### LINKED ISSUE #284: Add fixed intensity indicator concept
Add fixed intensity indicator concept (`::picolibrary::Indicator::Fixed_Intensity_Indicator_Concept`) and associated mock (`::picolibrary::Testing::Unit::Indicator::Mock_Fixed_Intensity_Indicator`).

Fixed intensity indicators will be expected to support the following operations:
- `auto initialize( Initial_Indicator_State initial_indicator_state = Initial_Indicator_State::EXTINGUISHED ) noexcept -> Result<Void, Error_Code>` or `auto initialize( Initial_Indicator_State initial_state = Initial_Indicator_State::EXTINGUISHED ) noexcept -> Result<Void, Void>`: initialize the indicator's hardware
- `auto illuminate() noexcept -> Result<Void, Error_Code>` or `auto illuminate() noexcept -> Result<Void, Void>`: illuminate the indicator
- `auto extinguish() noexcept -> Result<Void, Error_Code>` or `auto extinguish() noexcept -> Result<Void, Void>`: illuminate the indicator
- `auto toggle() noexcept -> Result<Void, Error_Code>` or `auto toggle() noexcept -> Result<Void, Void>`: toggle the state of the indicator

### PR DESCRIPTION
**Pull request by jaylamb**
Resolves #284.

### CODE REVIEW

File: include/picolibrary/indicator.h [hunk 1]
```diff
@@ -36,6 +40,67 @@ enum class Initial_Indicator_State {
...
+     * \brief Initialize the indicator's hardware.
+     *
+     * \param[in] initial_indicator_state The initial state of the indicator.
+     *
+     * \return Nothing if indicator hardware initialization succeeded.
+     * \return An error code if indicator hardware initialization failed. If indicator
+     *         hardware initialization cannot fail, return
+     *         picolibrary::Result<picolibrary::Void, picolibrary::Void>.
+     */
+    auto initialize( Initial_Indicator_State initial_state = Initial_Indicator_State::EXTINGUISHED ) noexcept
```
Comment (apcountryman) [inline include/picolibrary/indicator.h]: Please change `initial_state` (error in issue description) to `initial_indicator_state` for consistency with the parameter documentation and GPIO pin concepts.

```suggestion
    auto initialize( Initial_Indicator_State initial_indicator_state = Initial_Indicator_State::EXTINGUISHED ) noexcept
```

File: include/picolibrary/indicator.h [hunk 2]
```diff
@@ -36,6 +40,67 @@ enum class Initial_Indicator_State {
...
+     */
+    auto extinguish() noexcept -> Result<Void, Error_Code>;
+
+    /**
+     * \brief Toggle the indicator.
+     *
+     * \return Nothing if toggling the indicator succeeded.
+     * \return An error code if toggling the indicator failed. If toggling the indicator
+     *          cannot fail, return picolibrary::Result<picolibrary::Void,
+     *          picolibrary::Void>.
```
Comment (apcountryman) [inline include/picolibrary/indicator.h]: Please fix indentation of subsequent comment lines.

```suggestion
     * \return An error code if toggling the indicator failed. If toggling the indicator
     *         cannot fail, return picolibrary::Result<picolibrary::Void,
     *         picolibrary::Void>.
```

File: include/picolibrary/testing/unit/indicator.h [hunk 3]
```diff
@@ -23,6 +23,7 @@
 #ifndef PICOLIBRARY_TESTING_UNIT_INDICATOR_H
 #define PICOLIBRARY_TESTING_UNIT_INDICATOR_H
 
+#include "gmock/gmock.h"
 #include "picolibrary/indicator.h"
 #include "picolibrary/testing/unit/random.h"
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/indicator.h]: The header file is currently relying on indirect includes. Please update to "include what you use".

```suggestion
#include "gmock/gmock.h"
#include "picolibrary/error.h"
#include "picolibrary/indicator.h"
#include "picolibrary/result.h"
#include "picolibrary/testing/unit/random.h"
#include "picolibrary/void.h"
```

**Review by apcountryman — CHANGES_REQUESTED** [review]

**Review by apcountryman — APPROVED** [review]
No review findings.
