### PR TITLE
Overhaul unit testing mocks

### LINKED ISSUE #843: Overhaul unit testing mocks
Overhaul unit testing mocks (and any associated movable mock handles) as follows:
- Mocks (and any associated movable mock handles) should not be commented as they are mocking something that is already commented (there may be some exceptions to this)
- Mock move/copy constructor and assignment operators should be explicitly deleted
- Movable mock handles should be derived from `::picolibrary::Testing::Unit::Mock_Handle` to avoid move code repetition
- Each mock that has an associated movable mock handle should have a `handle()` member function that creates a handle to the mock
- Convenience type aliases should not be defined
- Closely related mock functions should be grouped together
- Mocks that simply add additional functionality to a simpler mock should derive from the simpler mock whenever possible

Mocks and movable mock handles:
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Blocking_Single_Sample_Converter`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Blocking_Single_Sample_Converter::Handle`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Non_Blocking_Single_Sample_Converter`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Non_Blocking_Single_Sample_Converter::Handle`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Blocking_Free_Running_Converter`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Blocking_Free_Running_Converter::Handle`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Non_Blocking_Free_Running_Converter`
- [x] `::picolibrary::Testing::Unit::ADC::Mock_Non_Blocking_Free_Running_Converter::Handle`
- [x] `::picolibrary::Testing::Unit::Asynchronous_Serial::Mock_Basic_Transmitter`
- [x] `::picolibrary::Testing::Unit::Asynchronous_Serial::Mock_Basic_Transmitter::Handle`
- [x] `::picolibrary::Testing::Unit::Asynchronous_Serial::Mock_Transmitter`
- [x] `::picolibrary::Testing::Unit::Asynchronous_Serial::Mock_Transmitter::Handle`
- [x] `::picolibrary::Testing::Unit::Mock_Error_Category`
- [x] `::picolibrary::Testing::Unit::Mock_Event_Category`
- [x] `::picolibrary::Testing::Unit::Mock_Event`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Input_Pin`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Input_Pin::Handle`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Internally_Pulled_Up_Input_Pin`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Internally_Pulled_Up_Input_Pin::Handle`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Output_Pin`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_Output_Pin::Handle`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_IO_Pin`
- [x] `::picolibrary::Testing::Unit::GPIO::Mock_IO_Pin::Handle`
- [x] `::picolibrary::Testing::Unit::I2C::Mock_Basic_Controller`
- [x] `::picolibrary::Testing::Unit::I2C::Mock_Basic_Controller::Handle`
- [x] `::picolibrary::Testing::Unit::I2C::Mock_Controller`
- [x] `::picolibrary::Testing::Unit::I2C::Mock_Controller::Handle`
- [x] `::picolibrary::Testing::Unit::I2C::Mock_Device<std::uint8_t>`
- [x] `::picolibrary::Testing::Unit::Indicator::Mock_Fixed_Intensity_Indicator`
- [x] `::picolibrary::Testing::Unit::Indicator::Mock_Fixed_Intensity_Indicator::Handle`
- [x] `::picolibrary::Testing::Unit::IP::Mock_Network_Stack`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Client`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Client::Handle`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Server`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Server::Handle`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Acceptor`
- [x] `::picolibrary::Testing::Unit::IP::TCP::Mock_Acceptor::Handle`
- [x] `::picolibrary::Testing::Unit::Microchip::MCP23008::Mock_Register_Cache`
- [x] `::picolibrary::Testing::Unit::Microchip::MCP23008::Mock_Driver`
- [x] `::picolibrary::Testing::Unit::Microchip::MCP3008::Mock_Driver`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Basic_Controller`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Basic_Controller::Handle`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Controller`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Controller::Handle`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Device_Selector`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Device_Selector::Handle`
- [x] `::picolibrary::Testing::Unit::SPI::Mock_Device`
- [x] `::picolibrary::Testing::Unit::Mock_Stream_Buffer`
- [x] `::picolibrary::Testing::Unit::Mock_Output_Formatter`
- [x] `::picolibrary::Testing::Unit::Mock_Output_Stream`
- [x] `::picolibrary::Testing::Unit::WIZnet::W5500::Mock_Communication_Controller`
- [x] `::picolibrary::Testing::Unit::WIZnet::W5500::Mock_Driver`
- [x] `::picolibrary::Testing::Unit::WIZnet::W5500::IP::Mock_Network_Stack`
- [x] `::picolibrary::Testing::Unit::WIZnet::W5500::IP::Mock_Client`
- [x] `::picolibrary::Testing::Unit::WIZnet::W5500::IP::Mock_Client::Handle`

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #843 (Overhaul unit testing mocks).

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [x] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/testing/unit/wiznet/w5500/ip/tcp.h [hunk 1]
```diff
@@ -43,539 +44,211 @@ namespace picolibrary::Testing::Unit::WIZnet::W5500::IP::TCP {
...
-        {
-            if ( &expression != this ) {
-                m_mock_client = expression.m_mock_client;
-
-                expression.m_mock_client = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/wiznet/w5500/ip/tcp.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

File: include/picolibrary/testing/unit/spi.h [hunk 2]
```diff
@@ -206,255 +109,87 @@ class Mock_Basic_Controller {
...
-        {
-            if ( &expression != this ) {
-                m_mock_controller = expression.m_mock_controller;
-
-                expression.m_mock_controller = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/spi.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

File: include/picolibrary/testing/unit/spi.h [hunk 3]
```diff
@@ -531,137 +246,53 @@ class Mock_Controller {
...
-        {
-            if ( &expression != this ) {
-                m_mock_device_selector = expression.m_mock_device_selector;
-
-                expression.m_mock_device_selector = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/spi.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

File: include/picolibrary/testing/unit/asynchronous_serial.h [hunk 4]
```diff
@@ -42,138 +43,52 @@ namespace picolibrary::Testing::Unit::Asynchronous_Serial {
...
-        {
-            if ( &expression != this ) {
-                m_mock_basic_transmitter = expression.m_mock_basic_transmitter;
-
-                expression.m_mock_basic_transmitter = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/asynchronous_serial.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

File: include/picolibrary/testing/unit/asynchronous_serial.h [hunk 5]
```diff
@@ -190,175 +105,71 @@ class Mock_Basic_Transmitter {
...
-        {
-            if ( &expression != this ) {
-                m_mock_transmitter = expression.m_mock_transmitter;
-
-                expression.m_mock_transmitter = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/asynchronous_serial.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

File: include/picolibrary/testing/unit/gpio.h [hunk 6]
```diff
@@ -535,175 +280,79 @@ class Mock_Output_Pin {
...
-        {
-            if ( &expression != this ) {
-                m_mock_io_pin = expression.m_mock_io_pin;
-
-                expression.m_mock_io_pin = nullptr;
-            } // if
-
-            return *this;
-        }
+        auto operator=( Handle && expression ) noexcept -> Handle & = default;
```
Comment (apcountryman) [inline include/picolibrary/testing/unit/gpio.h]:
```suggestion
        constexpr auto operator=( Handle && expression ) noexcept -> Handle & = default;
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
