### PR TITLE
Overhaul GPIO output pin based fixed intensity indicator automated tests

### LINKED ISSUE #2086: Overhaul GPIO output pin based fixed intensity indicator automated tests
Overhaul GPIO output pin based fixed intensity indicator (`::picolibrary::Indicator::GPIO_Output_Pin_Fixed_Intensity_Indicator`) automated tests.
- [x] Replace runtime random number generation with pre-generated random numbers
- [x] Remove trivial tests where appropriate
- [x] Replace test loops with value parameterized tests
- [x] Split tests with blocks into multiple named tests
- [x] Overhaul test style/structure

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #2086 (Overhaul GPIO output pin based fixed intensity indicator automated tests).

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [x] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: test/automated/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/main.cc
Comment (apcountryman) [inline test/automated/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/main.cc:1]: `<ostream>` include is missing.

File: test/automated/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/main.cc [hunk 1]
```diff
@@ -31,50 +31,116 @@ namespace {
...
-        } // for
-    }
+    EXPECT_CALL( indicator, initialize( test_case.initial_pin_state ) );
+
+    indicator.initialize( test_case.initial_indicator_state );
 }
 
+/**
+ * \brief picolibrary::Indicator::GPIO_Output_Pin_Fixed_Intensity_Indicator::initialize()
+ *        non-default argument test case.
```
Comment (apcountryman) [inline test/automated/picolibrary/indicator/gpio_output_pin_fixed_intensity_indicator/main.cc]:
```suggestion
 *        non-default argument test cases.
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
