### PR TITLE
Add fixed capacity vector

### LINKED ISSUE #852: Add fixed capacity vector
Add fixed capacity vector (`::picolibrary::Fixed_Capacity_Vector`).
- [x] The `Fixed_Capacity_Vector` class should be defined in the `include/picolibrary/vector.h`/`source/picolibrary/vector.cc` header/source file pair

The `Fixed_Capacity_Vector` class should have the following template arguments:
- [x] `typename T`: The vector element type
- [x] `std::size_t N`: The maximum number of elements in the vector

The `Fixed_Capacity_Vector` class should have the following member types:
- [x] `using Value = T;`: The vector element type
- [x] `using Size = std::size_t;`: The number of elements in the vector
- [x] `using Position = std::size_t;`: A vector element position
- [x] `using Reference = Value &;`: A reference to a vector element
- [x] `using Const_Reference = Value const &;`: A reference to a const vector element
- [x] `using Pointer = Value *;`: A pointer to a vector element
- [x] `using Const_Pointer = Value const *;`: A pointer to a const vector element
- [x] `using Iterator = Pointer;`: A vector iterator
- [x] `using Const_Iterator = Const_Pointer;`: A const vector iterator
- [x] `using Reverse_Iterator = std::reverse_iterator<Iterator>;`: A vector reverse iterator
- [x] `using Const_Reverse_Iterator = std::reverse_iterator<Const_Iterator>;`: A const vector reverse iterator

The `Fixed_Capacity_Vector` class should support the following operations:
- [x] `constexpr Fixed_Capacity_Vector() noexcept = default;`
- [x] `constexpr Fixed_Capacity_Vector( Size n, Value const & value ) noexcept;`
- [x] `constexpr explicit Fixed_Capacity_Vector( Size n ) noexcept;`
- [x] `template<typename Iterator> constexpr Fixed_Capacity_Vector( Iterator begin, Iterator end ) noexcept;`
- [x] `constexpr Fixed_Capacity_Vector( std::initializer_list<Value> initializer_list ) noexcept;`
- [x] `constexpr Fixed_Capacity_Vector( Fixed_Capacity_Vector && source ) noexcept;`
- [x] `constexpr Fixed_Capacity_Vector( Fixed_Capacity_Vector const & original ) noexcept;`
- [x] `~Fixed_Capacity_Vector() noexcept;`
- [x] `constexpr auto operator=( std::initializer_list<Value> initializer_list ) noexcept -> Fixed_Capacity_Vector &;`
- [x] `constexpr auto operator=( Fixed_Capacity_Vector && expression ) noexcept -> Fixed_Capacity_Vector &;`
- [x] `constexpr auto operator=( Fixed_Capacity_Vector const & expression ) noexcept -> Fixed_Capacity_Vector &;`
- [x] `constexpr auto assign( Size n, Value const & value ) noexcept -> Result<Void, Error_Code>;`: Replace the vector's contents with n copies of value
- [x] `template<typename Iterator> constexpr auto assign( Iterator begin, Iterator end ) noexcept -> Result<Void, Error_Code>;`: Replace the vector's contents with those in the provided range
- [x] `constexpr auto assign( std::initializer_list<Value> initializer_list ) noexcept -> Result<Void, Error_Code>;`: Replace the vector's contents with those in the provided initializer list
- [x] `auto operator[]( Position position ) noexcept -> Reference;`: Access the element at the specified position in the vector
- [x] `auto operator[]( Position position ) const noexcept -> Const_Reference;`: Access the element at the specified position in the vector
- [x] `auto at( Position position ) noexcept -> Result<std::reference_wrapper<Value>, Error_Code>;`: Access the element at the specified position in the vector
- [x] `auto at( Position position ) const noexcept -> Result<std::reference_wrapper<Value const>, Error_Code>;`: Access the element at the specified position in the vector
- [x] `auto front() noexcept -> Reference;`: Access the first element of the vector
- [x] `auto front() const noexcept -> Const_Reference;`: Access the first element of the vector
- [x] `auto back() noexcept -> Reference;`: Access the last element of the vector
- [x] `auto back() const noexcept -> Const_Reference;`: Access the last element of the vector
- [x] `auto data() noexcept -> Pointer;`: Access the underlying array
- [x] `auto data() const noexcept -> Const_Pointer;`: Access the underlying array
- [x] `auto begin() noexcept -> Iterator;`: Get an iterator to the first element of the vector
- [x] `auto begin() const noexcept -> Const_Iterator;`: Get an iterator to the first element of the vector
- [x] `auto cbegin() const noexcept -> Const_Iterator;`: Get an iterator to the first element of the vector
- [x] `auto end() noexcept -> Iterator;`: Get an iterator to the element following the last element of the vector
- [x] `auto end() const noexcept -> Const_Iterator;`: Get an iterator to the element following the last element of the vector
- [x] `auto cend() const noexcept -> Const_Iterator;`: Get an iterator to the element following the last element of the vector
- [x] `auto rbegin() noexcept -> Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
- [x] `auto rbegin() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
- [x] `auto crbegin() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
- [x] `auto rend() noexcept -> Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
- [x] `auto rend() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
- [x] `auto crend() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
- [x] `[[nodiscard]] constexpr auto empty() const noexcept -> bool;`: Check if the vector is empty
- [x] `constexpr auto size() const noexcept -> Size;`: Get the number of elements in the vector
- [x] `constexpr auto max_size() const noexcept -> Size;`: Get the maximum number of elements the vector is able to hold
- [x] `constexpr auto capacity() const noexcept -> Size;`: Get the number of elements the vector has allocated space for
- [x] `constexpr void clear() noexcept;`: Erase all vector elements
- [x] `constexpr auto insert( Const_Iterator position, Value const & value ) noexcept -> Result<Iterator, Error_Code>;`: Insert an element before the specified position in the vector
- [x] `constexpr auto insert( Const_Iterator position, Value && value ) noexcept -> Result<Iterator, Error_Code>;`: Insert an element before the specified position in the vector
- [x] `constexpr auto insert( Const_Iterator position, Size n, Value const & value ) noexcept -> Result<Iterator, Error_Code>;`: Insert n copies of value before the specified position in the vector
- [x] `template<typename Iterator> constexpr auto insert( Const_Iterator position, Iterator begin, Iterator end ) noexcept -> Result<Iterator, Error_Code>;`: Insert elements from the specified range before the specified position in the vector
- [x] `constexpr auto insert( Const_Iterator position, std::initializer_list<Value> initializer_list ) noexcept -> Result<Iterator, Error_Code>;`: Insert elements from the specified initializer list before the specified position in the vector
- [x] `template<typename ... Arguments> constexpr auto emplace( Const_Iterator position, Arguments && ... arguments ) noexcept -> Result<Iterator, Error_Code>;`: Emplace an element before the specified position in the vector
- [x] `constexpr auto erase( Const_Iterator position ) noexcept -> Iterator;`: Remove the element at the specified position in the vector
- [x] `constexpr auto erase( Const_Iterator begin, Const_Iterator end ) noexcept -> Iterator;`: Remove the elements at the specified range of positions in the vector
- [x] `constexpr auto push_back( Value const & value ) noexcept -> Result<Void, Error_Code>;`: Append an element to the end of the vector
- [x] `constexpr auto push_back( Value && value ) noexcept -> Result<Void, Error_Code>;`: Append an element to the end of the vector
- [x] `template<typename ... Arguments> constexpr auto emplace_back( Arguments && ... arguments ) noexcept -> Result<std::reference_wrapper<Value>, Error_Code>;`: Append an element to the end of the vector
- [x] `constexpr void pop_back() noexcept;`: Remove the last element of the vector
- [x] `constexpr auto resize( Size size ) noexcept -> Result<Void, Error_Code>;`: Resize the vector to be the specified size
- [x] `constexpr auto resize( Size size, Value const & value ) noexcept -> Result<Void, Error_Code>;`: Resize the vector to be the specified size

The `Fixed_Capacity_Vector` class should have the following non-member utilities:
- [x] `template<typename T> struct fixed_capacity_vector_capacity;`: Get the capacity of a fixed capacity vector
- [x] `template<typename T> constexpr auto fixed_capacity_vector_capacity_v;`: Get the capacity of a fixed capacity vector

The `Fixed_Capacity_Vector` class should support the following non-member operations (other comparison operators will be added later):
- [x] `template<typename T, std::size_t N> constexpr auto make_fixed_capacity_vector( std::size_t n, T const & value ) noexcept -> Result<Fixed_Capacity_Vector<T, N>, Error_Code>;`: Construct a fixed capacity vector
- [x] `template<typename T, std::size_t N> constexpr auto make_fixed_capacity_vector( std::size_t n ) noexcept -> Result<Fixed_Capacity_Vector<T, N>, Error_Code>;`: Construct a fixed capacity vector
- [x] `template<typename T, std::size_t N, typename Iterator> constexpr auto make_fixed_capacity_vector( Iterator begin, Iterator end ) noexcept -> Result<Fixed_Capacity_Vector<T, N>, Error_Code>;`: Construct a fixed capacity vector
- [x] `template<typename T, std::size_t N> constexpr auto make_fixed_capacity_vector( std::initializer_list<T> initializer_list ) noexcept -> Result<Fixed_Capacity_Vector<T, N>, Error_Code>;`: Construct a fixed capacity vector
- [x] `template<typename T, std::size_t LHS_N, std::size_t RHS_N> constexpr auto operator==( Fixed_Capacity_Vector<T, LHS_N> const & lhs, Fixed_Capacity_Vector<T, RHS_N> const & rhs ) noexcept -> bool;`
- [x] `template<typename T, std::size_t LHS_N, std::size_t RHS_N> constexpr auto operator!=( Fixed_Capacity_Vector<T, LHS_N> const & lhs, Fixed_Capacity_Vector<T, RHS_N> const & rhs ) noexcept -> bool;`

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #852 (Add fixed capacity vector).

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [x] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/vector.h [hunk 1]
```diff
@@ -0,0 +1,1326 @@
...
+
+    /**
+     * \brief A const vector iterator.
+     */
+    using Const_Iterator = Const_Pointer;
+
+    /**
+     * \brief A vector reverse iterator.
+     */
+    using Reverse_Iterator = std::reverse_iterator<Pointer>;
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
    using Reverse_Iterator = std::reverse_iterator<Iterator>;
```

File: include/picolibrary/vector.h [hunk 2]
```diff
@@ -0,0 +1,1326 @@
...
+    }
+
+    /**
+     * \brief Constructor.
+     *
+     * \warning This constructor does not validate its arguments. Use
+     *          picolibrary::make_fixed_capacity_vector( std::initializer_list<T> ) if
+     *          argument validation is desired.
+     *
+     * \param[in] initializer_list The initializer list to initialize the vector with.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \param[in] initializer_list The initializer list containing the values to
     *            initialize the vector with.
```

File: include/picolibrary/vector.h [hunk 3]
```diff
@@ -0,0 +1,1326 @@
...
+    }
+
+    /**
+     * \brief Assignment operator.
+     *
+     * \warning This function does not validate its arguments. Use
+     *          picolibrary::Fixed_Capacity_Vector::assign( std::initializer_list<Value> )
+     *          if argument validation is desired.
+     *
+     * \param[in] initializer_list The initializer list containing the values to assign to
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \param[in] initializer_list The initializer list containing the values to store in
```

File: include/picolibrary/vector.h [hunk 4]
```diff
@@ -0,0 +1,1326 @@
...
+     *            the vector.
+     *
+     * \return Nothing if the size of the initializer list is less than or equal to N.
+     * \return picolibrary::Generic_Error::INSUFFICIENT_CAPACITY if the size of the
+     *         initializer list is greater than N.
+     */
+    constexpr auto assign( std::initializer_list<Value> initializer_list ) noexcept
+        -> Result<Void, Error_Code>
+    {
+        if ( initializer_list.size() > N ) {} // if
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
        if ( initializer_list.size() > N ) {
            Generic_Error::INSUFFICIENT_CAPACITY;
        } // if
```

File: include/picolibrary/vector.h [hunk 5]
```diff
@@ -0,0 +1,1326 @@
...
+     * \brief Access the element at the specified position in the vector.
+     *
+     * \param[in] position The position of the vector element to access.
+     *
+     * \return The element at the specified position in the vector if the specified
+     *         position is a valid position.
+     * \return picolibrary::Generic_Error::OUT_OF_RANGE if the specified position is not a
+     *         valid position.
+     */
+    auto at( Position position ) noexcept -> Result<std::reference_wrapper<Value>, Error_Code>
```
Comment (apcountryman) [inline include/picolibrary/vector.h]: This function can be `constexpr` since it has an execution path that doesn't use `reinterpret_cast`.
```suggestion
    constexpr auto at( Position position ) noexcept -> Result<std::reference_wrapper<Value>, Error_Code>
```

File: include/picolibrary/vector.h [hunk 6]
```diff
@@ -0,0 +1,1326 @@
...
+     * \brief Access the element at the specified position in the vector.
+     *
+     * \param[in] position The position of the vector element to access.
+     *
+     * \return The element at the specified position in the vector if the specified
+     *         position is a valid position.
+     * \return picolibrary::Generic_Error::OUT_OF_RANGE if the specified position is not a
+     *         valid position.
+     */
+    auto at( Position position ) const noexcept
```
Comment (apcountryman) [inline include/picolibrary/vector.h]: This function can be `constexpr` since it has an execution path that doesn't use `reinterpret_cast`.
```suggestion
    constexpr auto at( Position position ) const noexcept
```

File: include/picolibrary/vector.h [hunk 7]
```diff
@@ -0,0 +1,1326 @@
...
+    {
+        for ( auto i = Size{}; i < m_size; ++i ) {
+            std::launder( reinterpret_cast<Pointer>( &m_storage[ i ] ) )->~Value();
+        } // for
+
+        m_size = 0;
+    }
+
+    /**
+     * \brief Insert an element before the specified position in the vector.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Insert a value before the specified position in the vector.
```

File: include/picolibrary/vector.h [hunk 8]
```diff
@@ -0,0 +1,1326 @@
...
+
+        new ( ++element ) Value{ value };
+
+        ++m_size;
+
+        return inserted_element;
+    }
+
+    /**
+     * \brief Insert an element before the specified position in the vector.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Insert a value before the specified position in the vector.
```

File: include/picolibrary/vector.h [hunk 9]
```diff
@@ -0,0 +1,1326 @@
...
+        return inserted_elements;
+    }
+
+    /**
+     * \brief Emplace an element before the specified position in the vector.
+     *
+     * \tparam Arguments Element construction argument types.
+     *
+     * \param[in] position The position to emplace the new element before.
+     * \param[in] arguments Element construction arguments.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Emplace a value before the specified position in the vector.
     *
     * \tparam Arguments Value construction argument types.
     *
     * \param[in] position The position to emplace the new value before.
     * \param[in] arguments Value construction arguments.
```

File: include/picolibrary/vector.h [hunk 10]
```diff
@@ -0,0 +1,1326 @@
...
+    }
+
+    /**
+     * \brief Remove the element at the specified position in the vector.
+     *
+     * \param[in] position The position of the element to remove.
+     *
+     * \return An iterator to the element following the removed element.
+     */
+    constexpr auto erase( Const_Iterator position ) noexcept -> Iterator
```
Comment (apcountryman) [inline include/picolibrary/vector.h]: This function can't be `constexpr` since it uses `reinterpret_cast`.
```suggestion
    auto erase( Const_Iterator position ) noexcept -> Iterator
```

File: include/picolibrary/vector.h [hunk 11]
```diff
@@ -0,0 +1,1326 @@
...
+
+    /**
+     * \brief Remove the elements at the specified range of positions in the vector.
+     *
+     * \param[in] begin The beginning of the range of elements to remove.
+     * \param[in] end The end of the range of elements to remove.
+     *
+     * \return An iterator to the element following the removed elements.
+     */
+    constexpr auto erase( Const_Iterator begin, Const_Iterator end ) noexcept -> Iterator
```
Comment (apcountryman) [inline include/picolibrary/vector.h]: This function can't be `constexpr` since it uses `reinterpret_cast`.
```suggestion
    auto erase( Const_Iterator begin, Const_Iterator end ) noexcept -> Iterator
```

File: include/picolibrary/vector.h [hunk 12]
```diff
@@ -0,0 +1,1326 @@
...
+            element->~Value();
+        } // for
+
+        m_size -= n;
+
+        return this->begin() + ( begin - this->begin() );
+    }
+
+    /**
+     * \brief Append an element to the end of the vector.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Append a value to the end of the vector.
```

File: include/picolibrary/vector.h [hunk 13]
```diff
@@ -0,0 +1,1326 @@
...
+
+        new ( &m_storage[ m_size ] ) Value{ value };
+
+        ++m_size;
+
+        return {};
+    }
+
+    /**
+     * \brief Append an element to the end of the vector.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Append a value to the end of the vector.
```

File: include/picolibrary/vector.h [hunk 14]
```diff
@@ -0,0 +1,1326 @@
...
+     *
+     * \tparam Arguments Element construction argument types.
+     *
+     * \param[in] arguments Element construction arguments.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
     * \brief Append a value to the end of the vector.
     *
     * \tparam Arguments Value construction argument types.
     *
     * \param[in] arguments Value construction arguments.
```

File: include/picolibrary/vector.h [hunk 15]
```diff
@@ -0,0 +1,1326 @@
...
+
+        ++m_size;
+
+        return back();
+    }
+
+    /**
+     * \brief Remove the last element of the vector.
+     */
+    constexpr void pop_back() noexcept
```
Comment (apcountryman) [inline include/picolibrary/vector.h]: This function can't be `constexpr` since it uses `reinterpret_cast`.
```suggestion
    void pop_back() noexcept
```

File: include/picolibrary/vector.h [hunk 16]
```diff
@@ -0,0 +1,1326 @@
...
+
+/**
+ * \brief Construct a fixed capacity vector.
+ *
+ * \relatedalso picolibrary::Fixed_Capacity_Vector
+ *
+ * \tparam T The vector element type.
+ * \tparam N The maximum number of elements in the vector.
+ *
+ * \param[in] n The number of copies of value to initialize the vector with.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \param[in] n The number of default constructed values to initialize the vector with.
```

File: include/picolibrary/vector.h [hunk 17]
```diff
@@ -0,0 +1,1326 @@
...
+ * \param[in] value The value to initialize the vector with n copies of.
+ *
+ * \return The vector if n is less than or equal to N.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \return The constructed vector if n is less than or equal to N.
```

File: include/picolibrary/vector.h [hunk 18]
```diff
@@ -0,0 +1,1326 @@
...
+ * \brief Construct a fixed capacity vector.
+ *
+ * \relatedalso picolibrary::Fixed_Capacity_Vector
+ *
+ * \tparam T The vector element type.
+ * \tparam N The maximum number of elements in the vector.
+ *
+ * \param[in] n The number of copies of value to initialize the vector with.
+ *
+ * \return The vector if n is less than or equal to N.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \return The constructed vector if n is less than or equal to N.
```

File: include/picolibrary/vector.h [hunk 19]
```diff
@@ -0,0 +1,1326 @@
...
+ * \relatedalso picolibrary::Fixed_Capacity_Vector
+ *
+ * \tparam T The vector element type.
+ * \tparam N The maximum number of elements in the vector.
+ * \tparam Iterator Range iterator.
+ *
+ * \param[in] begin The beginning of the range of values to initialize the vector with.
+ * \param[in] end The end of the range of values to initialize the vector with.
+ *
+ * \return The vector if the size of the range is less than or equal to N.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \return The constructed vector if the size of the range is less than or equal to N.
```

File: include/picolibrary/vector.h [hunk 20]
```diff
@@ -0,0 +1,1326 @@
...
+
+/**
+ * \brief Construct a fixed capacity vector.
+ *
+ * \relatedalso picolibrary::Fixed_Capacity_Vector
+ *
+ * \tparam T The vector element type.
+ * \tparam N The maximum number of elements in the vector.
+ *
+ * \param[in] initializer_list The initializer list to initialize the vector with.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \param[in] initializer_list The initializer list containing the values to initialize
 *            the vector with.
```

File: include/picolibrary/vector.h [hunk 21]
```diff
@@ -0,0 +1,1326 @@
...
+ *
+ * \return The vector if the size of the initializer list is less than or equal to N.
```
Comment (apcountryman) [inline include/picolibrary/vector.h]:
```suggestion
 * \return The constructed  vector if the size of the initializer list is less than or
 *         equal to N.
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
