### PR TITLE
Add fixed capacity vector

### LINKED ISSUE #1016: Add fixed capacity vector
Add fixed capacity vector (`::picolibrary::Fixed_Capacity_Vector`).
- [x] The `Fixed_Capacity_Vector` class should be defined in the `include/picolibrary/fixed_capacity_vector.h`/`source/picolibrary/fixed_capacity_vector.cc` header/source file pair
- [x] The `Fixed_Capacity_Vector` class should have the following template arguments:
    - [x] `typename T`: The vector element type
    - [x] `std::size_t N`: The maximum number of elements in the vector
- [x] The `Fixed_Capacity_Vector` class should have the following member type aliases:
    - [x] `using Value = T;`: The vector element type
    - [x] `using Size = std::size_t;`: The number of elements in the vector
    - [x] `using Position = std::size_t;`: A vector element position
    - [x] `using Reference = Value &;`: A reference to a vector element
    - [x] `using Const_Reference = Value const &;`: A reference to a const vector element
    - [x] `using Pointer = Value *;`: A pointer to a vector element
    - [x] `using Const_Pointer = Value const *;`: A pointer to a const vector element
    - [x] `using Iterator = Pointer;`: A vector iterator
    - [x] `using Const_Iterator = Const_Pointer;`: A const vector iterator
    - [x] `using Reverse_Iterator = std::reverse_iterator<Iterator>;`: A vector reverse iterator
    - [x] `using Const_Reverse_Iterator = std::reverse_iterator<Const_Iterator>;`: A const vector reverse iterator
- [x] The `Fixed_Capacity_Vector` class should support the following operations:
    - [x] `constexpr Fixed_Capacity_Vector() noexcept = default;`
    - [x] `constexpr Fixed_Capacity_Vector( Size n, Value const & value ) noexcept;`
    - [x] `constexpr explicit Fixed_Capacity_Vector( Size n ) noexcept;`
    - [x] `template<typename Iterator> constexpr Fixed_Capacity_Vector( Iterator begin, Iterator end ) noexcept;`
    - [x] `constexpr Fixed_Capacity_Vector( std::initializer_list<Value> initializer_list ) noexcept;`
    - [x] `constexpr Fixed_Capacity_Vector( Fixed_Capacity_Vector && source ) noexcept;`
    - [x] `constexpr Fixed_Capacity_Vector( Fixed_Capacity_Vector const & original ) noexcept;`
    - [x] `~Fixed_Capacity_Vector() noexcept;`
    - [x] `constexpr auto operator=( std::initializer_list<Value> initializer_list ) noexcept -> Fixed_Capacity_Vector &;`
    - [x] `constexpr auto operator=( Fixed_Capacity_Vector && expression ) noexcept -> Fixed_Capacity_Vector &;`
    - [x] `constexpr auto operator=( Fixed_Capacity_Vector const & expression ) noexcept -> Fixed_Capacity_Vector &;`
    - [x] `constexpr void assign( Size n, Value const & value ) noexcept;`: Replace the vector's contents with n copies of a value
    - [x] `template<typename Iterator> constexpr void assign( Iterator begin, Iterator end ) noexcept;`: Replace the vector's contents with those in the provided range
    - [x] `constexpr void assign( std::initializer_list<Value> initializer_list ) noexcept;`: Replace the vector's contents with those in the provided initializer list
    - [x] `auto operator[]( Position position ) noexcept -> Reference;`: Access the element at the specified position in the vector
    - [x] `auto operator[]( Position position ) const noexcept -> Const_Reference;`: Access the element at the specified position in the vector
    - [x] `auto at( Position position ) noexcept -> Reference;`: Access the element at the specified position in the vector
    - [x] `auto at( Position position ) const noexcept -> Const_Reference;`: Access the element at the specified position in the vector
    - [x] `auto front() noexcept -> Reference;`: Access the first element of the vector
    - [x] `auto front() const noexcept -> Const_Reference;`: Access the first element of the vector
    - [x] `auto back() noexcept -> Reference;`: Access the last element of the vector
    - [x] `auto back() const noexcept -> Const_Reference;`: Access the last element of the vector
    - [x] `auto data() noexcept -> Pointer;`: Access the underlying array
    - [x] `auto data() const noexcept -> Const_Pointer;`: Access the underlying array
    - [x] `auto begin() noexcept -> Iterator;`: Get an iterator to the first element of the vector
    - [x] `auto begin() const noexcept -> Const_Iterator;`: Get an iterator to the first element of the vector
    - [x] `auto cbegin() const noexcept -> Const_Iterator;`: Get an iterator to the first element of the vector
    - [x] `auto end() noexcept -> Iterator;`: Get an iterator to the element following the last element of the vector
    - [x] `auto end() const noexcept -> Const_Iterator;`: Get an iterator to the element following the last element of the vector
    - [x] `auto cend() const noexcept -> Const_Iterator;`: Get an iterator to the element following the last element of the vector
    - [x] `auto rbegin() noexcept -> Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
    - [x] `auto rbegin() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
    - [x] `auto crbegin() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the first element of the reversed vector
    - [x] `auto rend() noexcept -> Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
    - [x] `auto rend() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
    - [x] `auto crend() const noexcept -> Const_Reverse_Iterator;`: Get an iterator to the element following the last element of the reversed vector
    - [x] `[[nodiscard] constexpr auto empty() const noexcept -> bool;`: Check if the vector is empty
    - [x] `constexpr auto size() const noexcept -> Size;`: Get the number of elements in the vector
    - [x] `constexpr auto max_size() const noexcept -> Size;`: Get the maximum number of elements the vector is able to hold
    - [x] `constexpr auto capacity() const noexcept -> Size;`: Get the number of elements the vector has allocated space for
    - [x] `constexpr void clear() noexcept;`: Erase all vector elements
    - [x] `auto insert( Const_Iterator position, Value const & value ) noexcept -> Iterator;`: Insert a value before the specified position in the vector
    - [x] `auto insert( Const_Iterator position, Value && value ) noexcept -> Iterator;`: Insert a value before the specified position in the vector
    - [x] `auto insert( Const_Iterator position, Size n, Value const & value ) noexcept -> Iterator;`: Insert n copies of a value before the specified position in the vector
    - [x] `template<typename Iterator> auto insert( Const_Iterator position, Iterator begin, Iterator end ) noexcept -> Iterator;`: Insert values from the specified range before the specified position in the vector
    - [x] `auto insert( Const_Iterator position, std::initializer_list<Value> initializer_list ) noexcept -> Iterator;`: Insert values from the specified initializer list before the specified position in the vector
    - [x] `template<typename... Arguments> auto emplace( Const_Iterator position, Arguments &&... arguments ) noexcept -> Iterator;`: Emplace a value before the specified position in the vector
    - [x] `auto erase( Const_Iterator position ) noexcept -> Interator;`: Remove the element at the specified position in the vector
    - [x] `auto erase( Const_Iterator begin, Const_Iterator end ) noexcept -> Iterator;`: Remove the elements at the specified range of positions in the vector
    - [x] `void push_back( Value const & value ) noexcept;`: Append a value to the end of the vector
    - [x] `void push_back( Value && value ) noexcept;`: Append a value to the end of the vector
    - [x] `template<typename... Arguments> void emplace_back( Arguments &&... arguments ) noexcept;`: Append a value to the end of the vector
    - [x] `void pop_back() noexcept;`: Remove the last element of the vector
    - [x] `void resize( Size size ) noexcept;`: Resize the vector to be the specified size
    - [x] `void resize( Size size, Value const & value ) noexcept;`: Resize the vector to be the specified size
    - [x] `template<typename T, std::size_t LHS_N, std::size_t RHS_N> constexpr auto operator==( Fixed_Capacity_Vector<T, LHS_N> const & lhs, Fixed_Capacity_Vector<T, RHS_N> const & rhs ) noexcept -> bool;` (non-member)
    - [x] `template<typename T, std::size_t LHS_N, std::size_t RHS_N> constexpr auto operator!=( Fixed_Capacity_Vector<T, LHS_N> const & lhs, Fixed_Capacity_Vector<T, RHS_N> const & rhs ) noexcept -> bool;` (non-member)
- [x] The `Fixed_Capacity_Vector` class should have the following non-member utilities:
    - [x] `template<typename T> struct fixed_capacity_vector_capacity;`: Get the capacity of a fixed capacity vector
    - [x] `template<typename T> constexpr auto fixed_capacity_vector_capacity_v;`: Get the capacity of a fixed capacity vector
    - [x] `template<typename T, std::size_t N> struct fixed_capacity_vector_capacity<Fixed_Capacity_Vector<T, N>>;`: Get the capacity of a fixed capacity vector

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #1016 (Add fixed capacity vector).

This pull request:
- [ ] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [x] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/fixed_capacity_vector.h [hunk 1]
```diff
@@ -0,0 +1,1140 @@
...
+    {
+        expect( initializer_list.size() <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
+
+        ::picolibrary::for_each(
+            initializer_list.begin(),
+            initializer_list.end(),
+            [ storage = &m_storage[ 0 ] ]( auto value ) mutable noexcept {
+                new ( storage++ ) Value{ value };
+            } );
+    }
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: It should be possible to rewrite this constructor so that it delegates to the iterator based constructor.

File: include/picolibrary/fixed_capacity_vector.h [hunk 2]
```diff
@@ -0,0 +1,1140 @@
...
+
+        ::picolibrary::for_each(
+            initializer_list.begin(),
+            initializer_list.end(),
+            [ storage = &m_storage[ 0 ] ]( auto value ) mutable noexcept {
+                new ( storage++ ) Value{ value };
+            } );
+
+        return *this;
+    }
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: This function can be refactored to leverage the `assign( std::initializer_list<Value> )` function.

File: include/picolibrary/fixed_capacity_vector.h [hunk 3]
```diff
@@ -0,0 +1,1140 @@
...
+
+        m_size = initializer_list.size();
+
+        ::picolibrary::for_each(
+            initializer_list.begin(),
+            initializer_list.end(),
+            [ storage = &m_storage[ 0 ] ]( auto value ) mutable noexcept {
+                new ( storage++ ) Value{ value };
+            } );
+    }
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: This function can be refactored to leverage the `assign( Iterator, Iterator )` function.

File: include/picolibrary/fixed_capacity_vector.h [hunk 4]
```diff
@@ -0,0 +1,1140 @@
...
+    /**
+     * \brief Check if the vector is empty.
+     *
+     * \return true if the vector is empty.
+     * \return false if the vector is not empty.
+     */
+    [[nodiscard]] constexpr auto empty() const noexcept -> bool
+    {
+        return not size();
+    }
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: This function should be moved so that it appears at the start of the "capacity" function set and after the end of the "iterators" function set.

File: include/picolibrary/fixed_capacity_vector.h [hunk 5]
```diff
@@ -0,0 +1,1140 @@
...
+    {
+        for ( auto i = Size{}; i < m_size; ++i ) { data()[ i ]->~Value(); } // for
+
+        m_size = 0;
+    }
+
+    /**
+     * \brief Insert a value before the specified position in the vector.
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + 1 <=
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 6]
```diff
@@ -0,0 +1,1140 @@
...
+     *      picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \param[in] position The position to insert the value before.
+     * \param[in] value The value to insert.
+     *
+     * \return An iterator to the inserted element.
+     */
+    auto insert( Const_Iterator position, Value && value ) noexcept
+    {
+        expect( size() + 1 <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 7]
```diff
@@ -0,0 +1,1140 @@
...
+     * \param[in] value The value to insert n copies of.
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + n <=
+     *      picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \return An iterator to the inserted elements.
+     */
+    auto insert( Const_Iterator position, Size n, Value const & value ) noexcept
+    {
+        expect( size() + n <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 8]
```diff
@@ -0,0 +1,1140 @@
...
+            new ( element + n ) Value{ std::move( *element ) };
+
+            element->~Value();
+        } // for
+
+        auto const inserted_elements = element + 1;
+
+        while ( n-- ) { new ( ++element ) Value{ value }; } // while
+
+        m_size += n;
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h:742]: `m_size` needs to be updated before `n` is modified.

File: include/picolibrary/fixed_capacity_vector.h [hunk 9]
```diff
@@ -0,0 +1,1140 @@
...
+     *      <= picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \return An iterator to the inserted elements.
+     */
+    template<typename Iterator>
+    auto insert( Const_Iterator position, Iterator begin, Iterator end ) noexcept
+    {
+        auto const n = static_cast<Size>( end - begin );
+
+        expect( size() + n <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 10]
```diff
@@ -0,0 +1,1140 @@
...
+    }
+
+    /**
+     * \brief Insert values from the specified initializer list before the specified
+     *        position in the vector.
+     *
+     * \param[in] position The position to insert the values before.
+     * \param[in] initializer_list The initializer list containing the values to insert.
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + initializer_list.size() <=
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 11]
```diff
@@ -0,0 +1,1140 @@
...
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + 1 <=
+     *      picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \tparam Arguments Value construction argument types.
+     *
+     * \param[in] position The position to emplace the new value before.
+     * \param[in] arguments Value construction arguments.
+     *
+     * \return An iterator to the inserted element.
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]:
```suggestion
     * \return An iterator to the emplaced element.
```

File: include/picolibrary/fixed_capacity_vector.h [hunk 12]
```diff
@@ -0,0 +1,1140 @@
...
+     */
+    template<typename... Arguments>
+    auto emplace( Const_Iterator position, Arguments &&... arguments ) noexcept
+    {
+        expect( size() + 1 <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 13]
```diff
@@ -0,0 +1,1140 @@
...
+     * \brief Append a value to the vector.
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + 1 <=
+     *      picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \param[in] value The value to append to the vector.
+     */
+    constexpr void push_back( Value const & value ) noexcept
+    {
+        expect( size() + 1 <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 14]
```diff
@@ -0,0 +1,1140 @@
...
+     * \brief Append a value to the vector.
+     *
+     * \pre picolibrary::Fixed_Capacity_Vector::size() + 1 <=
+     *      picolibrary::Fixed_Capacity_Vector::max_size()
+     *
+     * \param[in] value The value to append to the vector.
+     */
+    constexpr void push_back( Value && value ) noexcept
+    {
+        expect( size() + 1 <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

File: include/picolibrary/fixed_capacity_vector.h [hunk 15]
```diff
@@ -0,0 +1,1140 @@
...
+     * \tparam Arguments Value construction argument types.
+     *
+     * \param[in] arguments Value construction arguments.
+     *
+     * \return A reference to the appended element.
+     */
+    template<typename... Arguments>
+    auto emplace_back( Arguments &&... arguments ) noexcept -> Reference
+    {
+        expect( size() + 1 <= max_size(), Generic_Error::INSUFFICIENT_CAPACITY );
```
Comment (apcountryman) [inline include/picolibrary/fixed_capacity_vector.h]: Add size wrap protection to precondition.

**Review by apcountryman — COMMENTED** [review]
No review findings.
