### PR TITLE
Fix WIZnet W5500 TCP over IP client socket SN_SR register value handling

### LINKED ISSUE #1735: Fix WIZnet W5500 TCP over IP client socket SN_SR register value handling
Fix WIZnet W5500 TCP over IP client socket (`::picolibrary::WIZnet::W5500::IP::TCP::Client`) SN_SR register value handling.

According to WIZnet forum posts (https://forum.wiznet.io/t/topic/5020/2 and https://forum.wiznet.io/t/topic/8883/2), there are SN_SR register values that are not documented in the datasheet, and these register values will not be disclosed due to WIZnet company policy.

- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L395
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L443
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L466
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L565
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L640
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L711
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L768
- [x] https://github.com/apcountryman/picolibrary/blob/7b72147c5b3b6b75c1bfd2d998d319a68b9d459c/include/picolibrary/wiznet/w5500/ip/tcp.h#L802

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #1735 (Fix WIZnet W5500 TCP over IP client socket SN_SR register value handling).

According to WIZnet forum posts (https://forum.wiznet.io/t/topic/5020/2 and https://forum.wiznet.io/t/topic/8883/2), there are SN_SR register values that are not documented in the datasheet, and these register values will not be disclosed due to WIZnet company policy.

This pull request:
- [x] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: include/picolibrary/wiznet/w5500.h [hunk 1]
```diff
@@ -1282,6 +1282,12 @@ struct SN_SR {
 
     /**
      * \brief Status.
+     *
+     * \warning This enum does not cover all valid register values since there are
+     *          register values that are not documented, and these register values will
+     *          not be disclosed due to WIZnet company policy (see
+     *          https://forum.wiznet.io/t/topic/5020/2 and
+     *          https://forum.wiznet.io/t/topic/8883/2).
```
Comment (apcountryman) [inline include/picolibrary/wiznet/w5500.h]:
```suggestion
     * \warning This enum does not cover all valid register values since there are
     *          register values that are not documented in the datasheet, and these
     *          register values will not be disclosed due to WIZnet company policy (see
     *          https://forum.wiznet.io/t/topic/5020/2 and
     *          https://forum.wiznet.io/t/topic/8883/2).
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
