### PR TITLE
Add fixed size array

### LINKED ISSUE #80: Add fixed size array
Add fixed size array (`::picolibrary::Fixed_Size_Array`) and the associated header/source file pair (`include/picolibrary/fixed_size_array.h` and `source/picolibrary/fixed_size_array.cc`).

The fixed size array will take the following template arguments:
- [x] `typename T`: the array element type
- [x] `std::size_t N`: the number of elements in the array

The fixed size array will initially provide the following type definitions:
- [x] `Value` (`T`): the array element type
- [x] `Size` (`std::size_t`): the number of elements in the array
- [x] `Position` (`std::size_t`): an array element position
- [x] `Reference` (`Value &`): a reference to an array element
- [x] `Const_Reference` (`Value const &`): a reference to a const array element
- [x] `Pointer` (`Value *`): a pointer to an array element
- [x] `Const_Pointer` (`Value const *`): a pointer to a const array element
- [x] `Iterator` (`Pointer`): an array iterator
- [x] `Const_Iterator` (`Const_Pointer`): a const array iterator

The fixed size array will initially support the following operations:
- [x] Construction (implicitly declared, use aggregate initialization)
- [x] Destruction (implicitly declared)
- [x] Assignment (implicitly declared)
- [x] `constexpr auto operator[]( Position position ) noexcept -> Reference`, `constexpr auto operator[]( Position position ) const noexcept -> Const_Reference`: access the element at the specified position in the array (no bounds checking)
- [x] `constexpr auto front() noexcept -> Reference`, `constexpr auto front() const noexcept -> Const_Reference`: access the first element of the array
- [x] `constexpr auto back() noexcept -> Reference`, `constexpr auto back() const noexcept -> Const_Reference`: access the last element of the array
- [x] `constexpr auto data() noexcept -> Pointer`, `constexpr auto data() const noexcept -> Const_Pointer`: access the underlying array
- [x] `constexpr auto begin() noexcept -> Iterator`, `constexpr auto begin() const noexcept -> Const_Iterator`, `constexpr auto cbegin() const noexcept -> Const_Iterator`: get an iterator to the first element of the array
- [x] `constexpr auto end() noexcept -> Iterator`, `constexpr auto end() const noexcept -> Const_Iterator`, `constexpr auto cend() const noexcept -> Const_Iterator`: get an iterator to the element following the last element of the array
- [x] `constexpr auto empty() const noexcept -> bool`: check if the array is empty
- [x] `constexpr auto size() const noexcept -> Size`: Get the number of elements in the array

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #80.

### CODE REVIEW

File: include/picolibrary/fixed_size_array.h [hunk 1]
```diff
@@ -0,0 +1,307 @@
...
+    Value m_array[ N ];
+
+    /**
+     * \brief Access the element at the specified position in the array.
+     *
+     * \param[in] position The position of the array element to access.
+     *
+     * \warning Bounds checking is not performed.
+     *
+     * \warning Calling this function on an empty array results in undefined behavior.
```
Comment (apcountryman) [inline include/picolibrary/fixed_size_array.h:92]: Remove blank line between warnings and move them to before the parameter documentation.

File: include/picolibrary/fixed_size_array.h [hunk 2]
```diff
@@ -0,0 +1,307 @@
...
+    }
+
+    /**
+     * \brief Access the element at the specified position in the array.
+     *
+     * \param[in] position The position of the array element to access.
+     *
+     * \warning Bounds checking is not performed.
+     *
+     * \warning Calling this function on an empty array results in undefined behavior.
```
Comment (apcountryman) [inline include/picolibrary/fixed_size_array.h:111]: Remove blank line between warnings and move them to before the parameter documentation.

File: include/picolibrary/fixed_size_array.h [hunk 3]
```diff
@@ -0,0 +1,307 @@
...
+        return begin() + size();
+    }
+
+    /**
+     * \brief Check if the array is empty.
+     *
+     * \return true if the array is empty.
+     * \return false if the array is not empty.
+     */
+    constexpr auto empty() const noexcept
```
Comment (apcountryman) [inline include/picolibrary/fixed_size_array.h]: This function should be marked `[[nodiscard]]`.

**Review by apcountryman — COMMENTED** [review]
No review findings.
