### PR TITLE
Fix hex dump output format specifier output formatter automated tests comments

### LINKED ISSUE #2095: Fix hex dump output format specifier output formatter automated tests comments
Fix hex dump output format specifier output formatter (`::picolibrary::Output_Formatter<::picolibrary::Format::Hex_Dump<Iterator>>`) automated tests comments.

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #2095 (Fix hex dump output format specifier output formatter automated tests comments).

This pull request:
- [x] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: test/automated/picolibrary/format/hex_dump/main.cc [hunk 1]
```diff
@@ -154,18 +158,19 @@ TEST_P( outputFormatterFormatHexDumpPrintOutputStream, worksProperly )
 INSTANTIATE_TEST_SUITE_P( testCases, outputFormatterFormatHexDumpPrintOutputStream, ValuesIn( outputFormatterFormatHexDumpPrint_TEST_CASES ) );
 
 /**
- * \brief picolibrary::Output_Formatter<Hex_Dump<Iterator>>::print(
+ * \brief picolibrary::Output_Formatter<picolibrary::Format::Hex_Dump<Iterator>>::print(
  *        picolibrary::Reliable_Output_Stream &, picolibrary::Format::Hex_Dump<Iterator>
- *        const & ) test fixture.
+ *        const &) test fixture.
```
Comment (apcountryman) [inline test/automated/picolibrary/format/hex_dump/main.cc]:
```suggestion
 *        const & ) test fixture.
```

File: test/automated/picolibrary/format/hex_dump/main.cc [hunk 2]
```diff
@@ -154,18 +158,19 @@ TEST_P( outputFormatterFormatHexDumpPrintOutputStream, worksProperly )
...
     public TestWithParam<outputFormatterFormatHexDumpPrint_Test_Case> {
 };
 
 /**
- * \brief Verify picolibrary::Output_Formatter<Hex_Dump<Iterator>>::print(
+ * \brief Verify
+ *        picolibrary::Output_Formatter<picolibrary::Format::Hex_Dump<Iterator>>::print(
  *        picolibrary::Reliable_Output_Stream &, picolibrary::Format::Hex_Dump<Iterator>
- *        const & ) works properly.
+ *        const &) works properly.
```
Comment (apcountryman) [inline test/automated/picolibrary/format/hex_dump/main.cc]:
```suggestion
 *        const & ) works properly.
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
